name: Build the SPFx WebPart

on: [push]

env:
  SolutionFolder: ../sp-list-utils

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Run npm ci
      run: npm ci
      working-directory: ${{ env.SolutionFolder }}
    
    - name: Run npm i -g gulp
      run: npm i -g gulp
      working-directory: ${{ env.SolutionFolder }}
    
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
      working-directory: ${{ env.SolutionFolder }}
